// Dummy AI Tools Data
export const aiTools = [
  {
    id: 1,
    name: "CodeWizard AI",
    logo: "🧙‍♂️",
    category: "Coding",
    rating: 4.8,
    users: "250K+",
    price: "Free",
    description: "Advanced code generation and debugging assistant powered by GPT-4",
    codingScore: 95,
    aptitudeScore: 88,
    tags: ["Python", "JavaScript", "Debugging"],
    reviews: 1203,
  },
  {
    id: 2,
    name: "DataMind Pro",
    logo: "🧠",
    category: "Productivity",
    rating: 4.7,
    users: "180K+",
    price: "Paid",
    description: "AI-powered data analysis and visualization tool for professionals",
    codingScore: 82,
    aptitudeScore: 92,
    tags: ["Analytics", "Visualization", "Business"],
    reviews: 892,
  },
  {
    id: 3,
    name: "QuizMaster AI",
    logo: "📝",
    category: "Aptitude",
    rating: 4.9,
    users: "320K+",
    price: "Free",
    description: "Smart quiz generation and assessment platform with adaptive learning",
    codingScore: 75,
    aptitudeScore: 96,
    tags: ["Education", "Assessment", "Learning"],
    reviews: 1567,
  },
  {
    id: 4,
    name: "DesignBot",
    logo: "🎨",
    category: "Productivity",
    rating: 4.6,
    users: "145K+",
    price: "Paid",
    description: "AI-driven design assistant for creating stunning visuals and layouts",
    codingScore: 68,
    aptitudeScore: 85,
    tags: ["Design", "Creative", "UI/UX"],
    reviews: 734,
  },
  {
    id: 5,
    name: "AlgoSolver",
    logo: "⚡",
    category: "Coding",
    rating: 4.8,
    users: "290K+",
    price: "Free",
    description: "LeetCode-style problem solver with real-time explanations",
    codingScore: 97,
    aptitudeScore: 89,
    tags: ["Algorithms", "DSA", "Interview Prep"],
    reviews: 2103,
  },
  {
    id: 6,
    name: "WriteCraft AI",
    logo: "✍️",
    category: "Productivity",
    rating: 4.5,
    users: "210K+",
    price: "Paid",
    description: "Professional writing assistant for content creation and editing",
    codingScore: 70,
    aptitudeScore: 90,
    tags: ["Writing", "Content", "Marketing"],
    reviews: 956,
  },
  {
    id: 7,
    name: "TestGenius",
    logo: "🎯",
    category: "Aptitude",
    rating: 4.7,
    users: "175K+",
    price: "Free",
    description: "Comprehensive aptitude test preparation with personalized feedback",
    codingScore: 76,
    aptitudeScore: 94,
    tags: ["Testing", "Aptitude", "CAT/GRE"],
    reviews: 845,
  },
  {
    id: 8,
    name: "DevAssist",
    logo: "💻",
    category: "Coding",
    rating: 4.9,
    users: "380K+",
    price: "Paid",
    description: "Complete development environment with AI pair programming",
    codingScore: 98,
    aptitudeScore: 87,
    tags: ["Full Stack", "DevOps", "Cloud"],
    reviews: 2456,
  },
];

// Dummy Courses Data
export const courses = [
  {
    id: 1,
    title: "Intro to Machine Learning",
    level: "Beginner",
    duration: "8 weeks",
    progress: 65,
    students: "45K+",
    rating: 4.8,
    lessons: 24,
    description: "Learn the fundamentals of ML with hands-on projects",
  },
  {
    id: 2,
    title: "Neural Networks Deep Dive",
    level: "Intermediate",
    duration: "10 weeks",
    progress: 30,
    students: "28K+",
    rating: 4.9,
    lessons: 32,
    description: "Master neural networks from scratch to advanced architectures",
  },
  {
    id: 3,
    title: "Prompt Engineering Mastery",
    level: "Beginner",
    duration: "4 weeks",
    progress: 85,
    students: "62K+",
    rating: 4.7,
    lessons: 16,
    description: "Craft effective prompts for any AI model",
  },
  {
    id: 4,
    title: "AI for Business",
    level: "Beginner",
    duration: "6 weeks",
    progress: 45,
    students: "38K+",
    rating: 4.6,
    lessons: 20,
    description: "Implement AI solutions in business contexts",
  },
  {
    id: 5,
    title: "Computer Vision Fundamentals",
    level: "Intermediate",
    duration: "12 weeks",
    progress: 20,
    students: "22K+",
    rating: 4.8,
    lessons: 36,
    description: "Build image recognition and object detection systems",
  },
  {
    id: 6,
    title: "Advanced NLP Techniques",
    level: "Advanced",
    duration: "14 weeks",
    progress: 10,
    students: "15K+",
    rating: 4.9,
    lessons: 42,
    description: "Master state-of-the-art natural language processing",
  },
];

// Dummy Leaderboard Data
export const leaderboard = [
  {
    rank: 1,
    name: "Alex Chen",
    avatar: "👨‍💻",
    score: 9850,
    badges: ["Coding Master", "AI Builder", "Top Contributor"],
    problemsSolved: 1247,
    streak: 156,
  },
  {
    rank: 2,
    name: "Sarah Johnson",
    avatar: "👩‍🔬",
    score: 9720,
    badges: ["Data Scientist", "Aptitude Pro", "Marathon Runner"],
    problemsSolved: 1189,
    streak: 142,
  },
  {
    rank: 3,
    name: "Michael Park",
    avatar: "👨‍🎓",
    score: 9580,
    badges: ["Quick Learner", "AI Researcher", "Problem Solver"],
    problemsSolved: 1156,
    streak: 128,
  },
  {
    rank: 4,
    name: "Emma Davis",
    avatar: "👩‍💼",
    score: 9450,
    badges: ["Full Stack Dev", "Team Player", "Innovator"],
    problemsSolved: 1098,
    streak: 115,
  },
  {
    rank: 5,
    name: "James Wilson",
    avatar: "👨‍🚀",
    score: 9320,
    badges: ["ML Engineer", "Code Ninja", "Mentor"],
    problemsSolved: 1045,
    streak: 98,
  },
  {
    rank: 6,
    name: "Lisa Anderson",
    avatar: "👩‍🏫",
    score: 9180,
    badges: ["Educator", "Content Creator", "Helper"],
    problemsSolved: 982,
    streak: 87,
  },
  {
    rank: 7,
    name: "David Kim",
    avatar: "👨‍💼",
    score: 9050,
    badges: ["System Architect", "Tech Lead", "Innovator"],
    problemsSolved: 945,
    streak: 76,
  },
  {
    rank: 8,
    name: "Rachel Martinez",
    avatar: "👩‍🔧",
    score: 8920,
    badges: ["DevOps Expert", "Cloud Specialist", "Automation Pro"],
    problemsSolved: 892,
    streak: 64,
  },
];

// Dummy Job Postings
export const jobPostings = [
  {
    id: 1,
    company: "TechCorp AI",
    logo: "🏢",
    position: "Senior ML Engineer",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$150K - $200K",
    posted: "2 days ago",
    applicants: 45,
    requiredScore: 8500,
  },
  {
    id: 2,
    company: "DataSystems Inc",
    logo: "📊",
    position: "AI Research Scientist",
    location: "Remote",
    type: "Full-time",
    salary: "$140K - $180K",
    posted: "5 days ago",
    applicants: 67,
    requiredScore: 9000,
  },
  {
    id: 3,
    company: "CloudNine Tech",
    logo: "☁️",
    position: "ML Infrastructure Engineer",
    location: "New York, NY",
    type: "Full-time",
    salary: "$130K - $170K",
    posted: "1 week ago",
    applicants: 52,
    requiredScore: 8000,
  },
  {
    id: 4,
    company: "BrightAI Solutions",
    logo: "💡",
    position: "Computer Vision Engineer",
    location: "Boston, MA",
    type: "Full-time",
    salary: "$125K - $165K",
    posted: "3 days ago",
    applicants: 38,
    requiredScore: 8200,
  },
  {
    id: 5,
    company: "NeuralNet Labs",
    logo: "🧬",
    position: "NLP Engineer",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$135K - $175K",
    posted: "4 days ago",
    applicants: 41,
    requiredScore: 8500,
  },
];

// Dummy Quiz Questions
export const quizQuestions = [
  {
    id: 1,
    question: "What is the primary purpose of backpropagation in neural networks?",
    options: [
      "To initialize weights",
      "To update weights based on error gradients",
      "To add more layers",
      "To reduce overfitting",
    ],
    correct: 1,
  },
  {
    id: 2,
    question: "Which activation function is most commonly used in hidden layers?",
    options: ["Sigmoid", "ReLU", "Linear", "Softmax"],
    correct: 1,
  },
  {
    id: 3,
    question: "What does GPU stand for in machine learning context?",
    options: [
      "General Processing Unit",
      "Graphics Processing Unit",
      "Gradient Processing Unit",
      "Grid Processing Unit",
    ],
    correct: 1,
  },
];

// Stats for Landing Page
export const stats = [
  { label: "AI Tools Ranked", value: "10,000+" },
  { label: "Active Users", value: "1M+" },
  { label: "Problems Solved", value: "5M+" },
  { label: "Success Rate", value: "94%" },
];
